//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MFLEX 的本地化字符串。
        /// </summary>
        internal static string APPLE_LBL {
            get {
                return ResourceManager.GetString("APPLE_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  -- {0}号机 的本地化字符串。
        /// </summary>
        internal static string DEVICE {
            get {
                return ResourceManager.GetString("DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel 2007格式|*.xlsx 的本地化字符串。
        /// </summary>
        internal static string EXCEL_FORMAT {
            get {
                return ResourceManager.GetString("EXCEL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功！ 的本地化字符串。
        /// </summary>
        internal static string EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string INFOR {
            get {
                return ResourceManager.GetString("INFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经打印条码数量{0}，到达本日的打印上限！ 的本地化字符串。
        /// </summary>
        internal static string MAX_LIMIT {
            get {
                return ResourceManager.GetString("MAX_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板文件{0}不存在 的本地化字符串。
        /// </summary>
        internal static string NO_TEMPLATE {
            get {
                return ResourceManager.GetString("NO_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定条件无打印数据！ 的本地化字符串。
        /// </summary>
        internal static string QUERY_NULL {
            get {
                return ResourceManager.GetString("QUERY_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个打印品目！ 的本地化字符串。
        /// </summary>
        internal static string SELECT_PRODUCT {
            get {
                return ResourceManager.GetString("SELECT_PRODUCT", resourceCulture);
            }
        }
    }
}
